spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: 1234567890
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver